---
- name: Check if Docker Compose is already installed
  shell: |
    {{ compose_path }} --version | grep -q "{{ compose_version }}"
  args:
    warn: false
  register: compose_installed
  failed_when: compose_installed.rc > 1

- name: Download Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
    dest: "{{ compose_path }}"
    mode: '0755'
  when: compose_installed.rc != 0

- name: Verify Docker Compose version
  shell: "{{ compose_path }} --version"
  register: compose_version_check
  changed_when: false

- name: Output Docker Compose version
  debug:
    msg: "Installed Docker Compose version: {{ compose_version_check.stdout }}"

- name: Create application directory
  file:
    path: /home/ec2-user/docker-compose-app
    state: directory

- name: Copy Docker Compose file
  copy:
    src: docker-compose.yml
    dest: /home/ec2-user/docker-compose-app/docker-compose.yml

- name: Copy Dockerfile
  copy:
    src: Dockerfile
    dest: /home/ec2-user/docker-compose-app/Dockerfile

- name: Copy Nginx configuration
  copy:
    src: nginx.conf
    dest: /home/ec2-user/docker-compose-app/nginx.conf

- name: Start Docker Compose
  shell: |
    cd /home/ec2-user/docker-compose-app
    docker-compose up -d
