version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www/html
    depends_on:
      - php
